/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "P_CH1_aliases.h"
#include "P_CH1.h"
#include "IDAC8_4.h"
#include "ADC_SAR_1.h"
#include "FLASH.h"
#include "isr_DAC_1.h"
#include "DMA_ADC_1_dma.h"
#include "DMA_DAC_1_dma.h"
#include "ADC_SAR_2.h"
#include "DMA_ADC_2_dma.h"
#include "pwmSAMPLING.h"
#include "IDAC8_3.h"
#include "clkADC.h"
#include "ShiftReg_4.h"
#include "DMA_DAC_2_dma.h"
#include "isr_DAC_2.h"
#include "ShiftReg_3.h"
#include "IDAC8_2.h"
#include "DMA_DAC_3_dma.h"
#include "isr_DAC_3.h"
#include "ShiftReg_2.h"
#include "IDAC8_1.h"
#include "DMA_DAC_4_dma.h"
#include "isr_DAC_4.h"
#include "ShiftReg_1.h"
#include "P_CH4_aliases.h"
#include "P_CH4.h"
#include "P_CH3_aliases.h"
#include "P_CH3.h"
#include "P_CH2_aliases.h"
#include "P_CH2.h"
#include "UART_1.h"
#include "refOut.h"
#include "isr_ADC_2.h"
#include "isr_ADC_1.h"
#include "LED_aliases.h"
#include "LED.h"
#include "Sig_inN_aliases.h"
#include "Sig_inN.h"
#include "ChannelSel.h"
#include "Sig_inP_aliases.h"
#include "Sig_inP.h"
#include "Track_Hold_2.h"
#include "Track_Hold_1.h"
#include "CompTrigger.h"
#include "isrTrigger.h"
#include "triggerIn_aliases.h"
#include "triggerIn.h"
#include "SW_aliases.h"
#include "SW.h"
#include "internTrigger.h"
#include "GND_XTAL_2_aliases.h"
#include "GND_XTAL_2.h"
#include "GND_XTAL_1_aliases.h"
#include "GND_XTAL_1.h"
#include "sigBuf.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_Bypass_aliases.h"
#include "ADC_SAR_1_Bypass.h"
#include "ADC_SAR_2_IRQ.h"
#include "ADC_SAR_2_Bypass_aliases.h"
#include "ADC_SAR_2_Bypass.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

